#### configuration

NAME          = teledactyl

THUNDERBIRD  ?= thunderbird
HOSTAPP      ?= $(THUNDERBIRD)
PROFILEPATHS ?= "$$HOME/.thunderbird" \
		"$$HOME/Library/Thunderbird" \
		"$$APPDATA/Thunderbird" \
		"$$AppData/Thunderbird"

include ../common/Makefile
