#### configuration

NAME          = melodactyl

SONGBIRD     ?= songbird
HOSTAPP      ?= $(SONGBIRD)
PROFILEPATHS ?= "$$HOME/.songbird2" \
		"$$HOME/Library/Songbird2" \
		"$$APPDATA/Songbird2"

include ../common/Makefile
