#### configuration

NAME          = melodactyl

FIREFOX      ?= songbird
HOSTAPP      ?= $(SONGBIRD)
PROFILEPATHS ?= "$$HOME/.songbird" \
		"$$HOME/Library/Songbird" \
		"$$APPDATA/Songbird"

include ../common/Makefile
